### PR TITLE
Updated class name. Added functions isFull() count(). Updated reame

### PR DESCRIPTION
**Pull request by vascojdb**
Changed name Queue to DataQueue because of ESP8266 already including a conflicting name. This will solve the compilation errors.
Added a maximum limit for number of messages in queue, defaults to 100, added function isFull() and count().
Completed the README file with more info.

### CODE REVIEW

**Review by vascojdb — COMMENTED** [review]
I have just noticed my tabs/spaces are not correct. If you want you can cancel this merge request, and i can update the spaces to tabs.

**Review by EinarArnason — CHANGES_REQUESTED** [review]
The name of Arduino.h is case sensitive for Linux users. You may want to make the counter variable size dynamic. Hard coded limits may be inconvenient for users as memory capabilities vary.

**Comment by vascojdb** [comment]
@EinarArnason , any tips on how to make the counter variable size dynamic? I would use int as then it will depend on the MCU being used, but maybe there is another way I am not aware of

**Comment by EinarArnason** [comment]
@vascojdb Personally I would use unsigned int, it will adapt to the cpu register size on compile. Perhaps it would be nice to let the user declare max memory size allowed for the queue to prevent system lockup due to full memory.

**Comment by vascojdb** [comment]
Will create the pull requests again with the new code

**Pull request closed without merging**
